name: Dependent-jobs-lab
on: [push]
jobs:
    first-job:
        runs-on: self-hosted
        steps:
            -   name: echo-job-name
                run: |
                    echo "JOB_ONE_MSG=wait" >> $GITHUB_ENV

    second-job:
        needs: first-job
        runs-on: self-hosted
        steps:
            -   name: echo-job-name
                run: echo "Msg from job one [${{ env.JOB_ONE_MSG}}]"