name: Dependent-jobs-lab
on: [push]
jobs:
    firstJob:
        runs-on: self-hosted
        outputs:
            msg: ${{ steps.job-msg.outputs.msg }}
        steps:
            -   id: job-msg
                name: echo-job-name
                run: echo "msg=wait" >> "$GITHUB_OUTPUT"

    second-job:
        needs: firstJob
        runs-on: self-hosted
        steps:
            -   name: echo-job-name
                env:
                    MSG: ${{needs.firstJob.outputs.msg}}
                run: |
                    echo "$MSG"