# If you don't create a self-hosted runner you will see:
# Waiting for a runner to pick up this job...
name: Self-hosted Mac & Workflow commands

on:
  push:
    branches:
      - main

jobs:
  workflow-cmds-job:
    runs-on: self-hosted
    steps:
      - name: GroupLogMsg
        run: |
          echo "::group::Labgroup"
          echo "This is one line"
          echo "And this is another line"
          echo "::endgroup::"
      - name: SetEnvVar
        run: |
          echo "LAB_ENV_VAR="Hi Github"" >> $GITHUB_ENV
      - name: PrintEnvVar
        run: |
          echo $LAB_VAR